version: '3.7'
services:
  ordermanagementservice:
    container_name: ordermanagementservice
    image: ordermanagementservice:0.0.1
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - backend_network
    
networks:
  backend_network: