INSERT INTO ORDER_DETAILS VALUES (1, SYSDATE, 'Order Placed', '20');
INSERT INTO ORDER_DETAILS VALUES (2, SYSDATE, 'In Progress', '50');
INSERT INTO ORDER_DETAILS VALUES (3, SYSDATE, 'Dispatched', '80');
INSERT INTO ORDER_DETAILS VALUES (4, SYSDATE, 'Delivered', '200');